
# Streamlit Cloud secrets example
DATABASE_URL = "postgresql+psycopg://USER:PASS@HOST:5432/DBNAME"

[supabase]
url = "https://your-project.supabase.co"
key = "YOUR-SUPABASE-ANON-OR-SERVICE-KEY"
bucket = "uploads"

[smtp]
host = "smtp.seuprovedor.com"
port = 465
user = "no-reply@seusistema.com"
password = "SENHA_AQUI"
from = "no-reply@seusistema.com"
